// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "me3dev-20200310095728-hostingbucket-local",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://me3dev-20200310095728-hostingbucket-local.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
