// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:16d2876a-7332-446c-8ef8-a2ac7ddcb878",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_O64QKNEJZ",
    "aws_user_pools_web_client_id": "1bddgap21vn7bdkqfpqjhhpj81",
    "oauth": {
        "domain": "me3cogauth213d8a8d-213d8a8d-local.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:3000/",
        "redirectSignOut": "https://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "me3cognito-20200224093634-hostingbucket-local",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://me3cognito-20200224093634-hostingbucket-local.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
